#!/usr/bin/env bash
set -u -o pipefail

main_con_name=caddy

log() {
	echo "$(date -R)": "$1"
}

docker_network_join() {
	docker network connect -- "$1" "$2"
	log connect $main_con_name to "$1"
}

docker_network_disconnect_if_alone() {
	con_name=$(docker network inspect -f "{{ range .Containers }}{{ .Name }}{{ end }}" -- "$1")
	if [ "$con_name" == "$2" ]
	then
		docker network disconnect -- "$1" "$2"
		log disconnect "$2" from "$1"
	fi
}

docker network ls --format '{{.Name}}' --filter driver=bridge | grep -vx -- bridge | \
while read -r network; do
	docker_network_disconnect_if_alone "$network" $main_con_name
	docker_network_join "$network" $main_con_name
done

event_format='{{if .Action}}{{slice .Action 0 1}} {{.Actor.Attributes.name}}{{end}}'
log "Waiting event..."
docker events -f type=network -f event=create -f event=disconnect --format "$event_format" | \
while read -r event; do
	e=${event::1}
	id=${event:2}
	case $e in
		c)
			docker_network_join "$id" $main_con_name
			;;
		d)
			docker_network_disconnect_if_alone "$id" $main_con_name
			;;
		*)
			log Unknown event: \'"$event"\'
	esac
done
